Repository wasd0/kinolove, pull requests merged in 2024-07, with the labels that each got.

#13 k-10 implement graceful shutdown
  cmd/kinolove/main.go
  internal/app/app.go
  internal/storage/postgresql.go
  pkg/logger/zerolog/zerolog.go
  pkg/utils/app/closer.go
Labels: enhancement

#14 Dev
  cmd/kinolove/main.go
  internal/app/app.go
  internal/storage/postgresql.go
  pkg/logger/zerolog/zerolog.go
  pkg/utils/app/closer.go
Labels: enhancement

#20 k-8 fix not found exception
  api/apiModel/model.go
Labels: bug

#25 k-17 создан скрипт миграции для windows. Добавил пример .env файла дл…
  .env.example.windows
  scripts/migrations_run.bat
Labels: enhancement

#27 Dev
  .env.example.windows
  scripts/migrations_run.bat
Labels: enhancement

#28 16 authentication api
  .env.example
  .env.example.windows
  api/api.go
  api/apiModel/login/login.go
  api/apiModel/user/user.go
  api/defaultApi.go
  api/loginApi.go
  api/movieApi.go
  go.mod
  go.sum
  internal/api/chi/server.go
  internal/app/apiProvider/apiProvider.go
  internal/app/app.go
  internal/app/repoProvider/repoProvider.go
  internal/app/serviceProvider/serviceProvider.go
  internal/repository/movieRepository.go
  internal/repository/permissionRepository.go
  internal/repository/repository.go
  internal/repository/roleRepository.go
  internal/repository/userRepository.go
  internal/service/authService.go
  internal/service/dto/login.go
  internal/service/dto/permission.go
  internal/service/loginService.go
  internal/service/movieService.go
  internal/service/permissionService.go
  internal/service/roleService.go
  internal/service/servErr.go
  internal/service/service.go
  internal/service/userService.go
  internal/utils/mapper/permissionMapper.go
  internal/utils/validator/userValidator.go
  pkg/constants/paths.go
  pkg/logger/chiLogger.go
  pkg/logger/logger.go
  pkg/logger/zerolog/zerolog.go
  pkg/utils/jwt/auth.go
  pkg/utils/jwt/token.go
Labels: enhancement

#29 Dev
  .env.example
  .env.example.windows
  api/api.go
  api/apiModel/login/login.go
  api/apiModel/user/user.go
  api/defaultApi.go
  api/loginApi.go
  api/movieApi.go
  go.mod
  go.sum
  internal/api/chi/server.go
  internal/app/apiProvider/apiProvider.go
  internal/app/app.go
  internal/app/repoProvider/repoProvider.go
  internal/app/serviceProvider/serviceProvider.go
  internal/repository/movieRepository.go
  internal/repository/permissionRepository.go
  internal/repository/repository.go
  internal/repository/roleRepository.go
  internal/repository/userRepository.go
  internal/service/authService.go
  internal/service/dto/login.go
  internal/service/dto/permission.go
  internal/service/loginService.go
  internal/service/movieService.go
  internal/service/permissionService.go
  internal/service/roleService.go
  internal/service/servErr.go
  internal/service/service.go
  internal/service/userService.go
  internal/utils/mapper/permissionMapper.go
  internal/utils/validator/userValidator.go
  pkg/constants/paths.go
  pkg/logger/chiLogger.go
  pkg/logger/logger.go
  pkg/logger/zerolog/zerolog.go
  pkg/utils/jwt/auth.go
  pkg/utils/jwt/token.go
Labels: enhancement

#30 7 auth service
  .env.example.unix
  README.md
  api/api.go
  api/defaultApi.go
  api/loginApi.go
  api/movieApi.go
  api/userApi.go
  internal/api/chi/server.go
  internal/app/apiProvider/apiProvider.go
  internal/app/app.go
  internal/app/serviceProvider/serviceProvider.go
  internal/consts/perms/perms.go
  internal/entity/.gen/kinolove/public/model/permissions.go
  internal/entity/.gen/kinolove/public/model/roles_permissions.go
  internal/entity/.gen/kinolove/public/model/users_permissions.go
  internal/entity/.gen/kinolove/public/table/permissions.go
  internal/entity/.gen/kinolove/public/table/roles_permissions.go
  internal/entity/.gen/kinolove/public/table/users_permissions.go
  internal/middleware/authorization.go
  internal/service/authService.go
  internal/service/loginService.go
  internal/service/service.go
  internal/utils/mapper/permissionMapper.go
  pkg/utils/jwt/token.go
  pkg/utils/jwtUtils/auth.go
  pkg/utils/jwtUtils/token.go
  storage/migrations/20240727190743_drop_global_lvl_perm.sql
Labels: enhancement

#31 Dev
  .env.example.unix
  README.md
  api/api.go
  api/defaultApi.go
  api/loginApi.go
  api/movieApi.go
  api/userApi.go
  internal/api/chi/server.go
  internal/app/apiProvider/apiProvider.go
  internal/app/app.go
  internal/app/serviceProvider/serviceProvider.go
  internal/consts/perms/perms.go
  internal/entity/.gen/kinolove/public/model/permissions.go
  internal/entity/.gen/kinolove/public/model/roles_permissions.go
  internal/entity/.gen/kinolove/public/model/users_permissions.go
  internal/entity/.gen/kinolove/public/table/permissions.go
  internal/entity/.gen/kinolove/public/table/roles_permissions.go
  internal/entity/.gen/kinolove/public/table/users_permissions.go
  internal/middleware/authorization.go
  internal/service/authService.go
  internal/service/loginService.go
  internal/service/service.go
  internal/utils/mapper/permissionMapper.go
  pkg/utils/jwt/token.go
  pkg/utils/jwtUtils/auth.go
  pkg/utils/jwtUtils/token.go
  storage/migrations/20240727190743_drop_global_lvl_perm.sql
Labels: enhancement

#32 k-7 replace constants to pkg
  api/movieApi.go
  api/userApi.go
  internal/service/authService.go
  pkg/constants/perms/perms.go
  pkg/utils/jwtUtils/auth.go
Labels: invalid

#33 Dev
  api/movieApi.go
  api/userApi.go
  internal/service/authService.go
  pkg/constants/perms/perms.go
  pkg/utils/jwtUtils/auth.go
Labels: invalid

#34 cors
  api/loginApi.go
  go.mod
  go.sum
  internal/api/chi/server.go
Labels: enhancement

#36 fix cors
  api/loginApi.go
  api/movieApi.go
  internal/api/chi/server.go
  internal/app/serviceProvider/serviceProvider.go
  internal/service/loginService.go
  internal/service/service.go
  internal/service/userService.go
Labels: bug

#37 Dev
  api/loginApi.go
  api/movieApi.go
  internal/api/chi/server.go
  internal/app/serviceProvider/serviceProvider.go
  internal/service/loginService.go
  internal/service/service.go
  internal/service/userService.go
Labels: bug
